// CODEMAP.md: the project tree with a one-line purpose per file, taken from each file's header comment.
// Deterministic (no model), so it can be regenerated and checked on every task.

const SOURCE = /\.(m?[jt]sx?|cjs|py|go|rs|java|kt|cs|rb|php|swift|sh|ps1|sql|vue|svelte)$/i;

export function purposeOf(path, text) {
  if (!SOURCE.test(path)) return undefined;
  const lines = String(text).split(/\r?\n/);
  let i = 0;
  if (lines[0]?.startsWith('#!')) i = 1;
  while (i < lines.length && !lines[i].trim()) i++;
  const l = (lines[i] || '').trim();
  const pick = (s) => { const t = s.trim(); return t.length >= 3 ? t : null; };
  let m;
  if ((m = /^\/\/+\s*(.*)$/.exec(l))) return pick(m[1]);
  if ((m = /^\/\*+\s*(.*?)\s*(\*\/)?$/.exec(l))) return pick(m[1].replace(/\*\/$/, ''));
  if ((m = /^"""\s*(.*?)\s*(""")?$/.exec(l)) || (m = /^'''\s*(.*?)\s*(''')?$/.exec(l))) return pick(m[1]);
  if ((m = /^#\s*(.*)$/.exec(l))) return pick(m[1]);
  if ((m = /^--\s*(.*)$/.exec(l))) return pick(m[1]);
  if ((m = /^<!--\s*(.*?)\s*(-->)?$/.exec(l))) return pick(m[1]);
  return null;
}

export function missingPurposeHeaders(files, paths) {
  return paths.filter((p) => files[p] !== undefined && purposeOf(p, files[p]) === null);
}

export function buildCodemap(files) {
  const tree = {};
  for (const p of Object.keys(files).sort()) {
    const parts = p.split('/');
    let node = tree;
    for (const dir of parts.slice(0, -1)) node = (node[dir + '/'] = node[dir + '/'] || {});
    node[parts.at(-1)] = p;
  }
  const lines = ['# Code map', '', '_Generated by Ghostship from file purpose headers. Do not edit by hand: run `gs codemap`._', '', '```text'];
  const walk = (node, depth) => {
    for (const [name, v] of Object.entries(node).sort(([a], [b]) => (a.endsWith('/') === b.endsWith('/') ? a.localeCompare(b) : a.endsWith('/') ? -1 : 1))) {
      const pad = '  '.repeat(depth);
      if (typeof v === 'object') { lines.push(`${pad}${name}`); walk(v, depth + 1); continue; }
      const purpose = purposeOf(v, files[v]);
      lines.push(purpose === undefined ? `${pad}${name}` : `${pad}${name} — ${purpose ?? '⚠ no purpose header'}`);
    }
  };
  walk(tree, 0);
  lines.push('```', '');
  return lines.join('\n');
}
