// The SDLC document set: which files each tier ships, scaffolding them from templates, checking they are
// filled in, the generated traceability matrix, and the CI workflow file.
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { load } from './store.mjs';
import { loadConfig } from './config.mjs';
import { parseContract } from './contract.mjs';
import { slug } from './markdown.mjs';
import { tryGit } from './git.mjs';
import { DOCS } from './paths.mjs';

export const TODO_MARK = '<!-- ghostship:todo';
const LIGHT = ['05-code/DEVELOPER-GUIDE.md', '06-quality/TEST-PLAN.md', '08-operations/RUNBOOK.md', '09-user-guides/USER-HANDBOOK.md'];
const STANDARD = [...LIGHT, '05-code/CODING-STANDARDS.md', '07-security/SECURITY-REPORT.md', '08-operations/CI-CD.md', '08-operations/DEPLOYMENT.md', '08-operations/CONFIG-REFERENCE.md', '09-user-guides/FAQ.md'];
const FULL = [...STANDARD, '08-operations/BACKUP-RECOVERY.md', '08-operations/MONITORING.md', '09-user-guides/ADMIN-GUIDE.md'];
export const REQUIRED_DOCS = { light: LIGHT, standard: STANDARD, full: FULL };
const MEMORY = ['MEMORY', 'DECISIONS', 'FAILED-APPROACHES', 'LESSONS', 'BASELINES', 'SKILL-CHANGES'].map((f) => `11-memory/${f}.md`);

export function scaffold(root, coreDir, { tier } = {}) {
  const t = tier || loadConfig(root).project?.tier || 'standard';
  const created = [];
  for (const rel of [...(REQUIRED_DOCS[t] || STANDARD), ...MEMORY]) {
    const dst = join(root, 'docs', rel);
    if (existsSync(dst)) continue;
    const src = join(coreDir, 'templates', 'docs', rel);
    if (!existsSync(src)) continue;
    mkdirSync(dirname(dst), { recursive: true });
    writeFileSync(dst, readFileSync(src, 'utf8'));
    created.push(`docs/${rel}`);
  }
  return created;
}

export function check(root, { tier } = {}) {
  const t = tier || loadConfig(root).project?.tier || 'standard';
  const missing = [], unfilled = [];
  for (const rel of REQUIRED_DOCS[t] || STANDARD) {
    const p = join(root, 'docs', rel);
    if (!existsSync(p)) { missing.push(`docs/${rel}`); continue; }
    const txt = readFileSync(p, 'utf8');
    if (txt.includes(TODO_MARK) || /^\s*(\|.*)?TODO\b/m.test(txt)) unfilled.push(`docs/${rel}`);
  }
  const api = ['yaml', 'yml', 'json'].map((x) => `${DOCS.design}/api/openapi.${x}`).find((f) => existsSync(join(root, f)));
  return { ok: !missing.length && !unfilled.length, missing, unfilled, openapi: api || null };
}

/** PRD sections → checks → tasks → acceptance tests → merge commits. */
export function traceability(root) {
  const state = load(root);
  const prd = existsSync(join(root, DOCS.prd)) ? readFileSync(join(root, DOCS.prd), 'utf8') : '';
  const sections = [...prd.matchAll(/^##\s+(.+)$/gm)].map((m) => ({ title: m[1].trim(), slug: slug(m[1]) }));
  const contract = existsSync(join(root, DOCS.acceptance)) ? parseContract(readFileSync(join(root, DOCS.acceptance), 'utf8')) : { checks: [] };
  let tests = [];
  try { tests = readdirSync(join(root, 'tests/acceptance')); } catch { /* none */ }
  const tasks = Object.values(state.tasks || {});
  const rows = contract.checks.map((c) => {
    const src = (c.source || '').replace(/^PRD#/i, '');
    const sec = sections.find((s) => s.slug === slug(src) || s.title.toLowerCase() === src.toLowerCase());
    const ts = tasks.filter((t) => t.checks.includes(c.id) && t.status !== 'DROPPED');
    return { check: c.id, text: c.text, kind: c.kind, requirement: sec ? sec.title : (c.source || '-'), tests: tests.filter((f) => f.startsWith(`${c.id}-`)),
      tasks: ts.map((t) => `${t.id} (${t.status}${t.merged?.commit ? ` ${t.merged.commit.slice(0, 8)}` : ''})`) };
  });
  const uncoveredSections = sections.filter((s) => !rows.some((r) => r.requirement === s.title)).map((s) => s.title);
  const e = (s) => String(s).replace(/\|/g, '\\|');
  const md = ['# Traceability', '', '_Generated by Ghostship from the PRD, the acceptance checks, the tasks and the acceptance tests. Do not edit._', '',
    '| requirement | check | kind | acceptance tests | tasks |', '|---|---|---|---|---|',
    ...rows.map((r) => `| ${e(r.requirement)} | ${r.check}: ${e(r.text)} | ${r.kind} | ${r.tests.map((t) => `\`${t}\``).join(' ') || '-'} | ${r.tasks.join(', ') || '-'} |`), '',
    '## PRD sections with no check', ...(uncoveredSections.length ? uncoveredSections.map((s) => `- ${s} (out of scope, context, or a gap)`) : ['- none']), ''].join('\n');
  mkdirSync(join(root, 'docs/01-requirements'), { recursive: true });
  writeFileSync(join(root, DOCS.traceability), md);
  return { path: DOCS.traceability, rows, uncoveredSections };
}

export function ciWorkflow(root) {
  const cfg = loadConfig(root);
  const c = cfg.commands || {};
  const acc = c.acceptance ? c.acceptance.replace('{files}', 'tests/acceptance/*') : '';
  const node = (() => { try { return JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).engines?.node?.match(/\d+/)?.[0] || '22'; } catch { return '22'; } })();
  const steps = [
    '      - uses: actions/checkout@v4', '        with:', '          fetch-depth: 0',
    '      - uses: actions/setup-node@v4', '        with:', `          node-version: "${node}"`,
    ...(existsSync(join(root, 'package-lock.json')) ? ['      - run: npm ci'] : existsSync(join(root, 'package.json')) ? ['      - run: npm install'] : []),
    ...(c.lint ? [`      - name: Lint`, `        run: ${c.lint}`] : []),
    ...(c.typecheck ? [`      - name: Typecheck`, `        run: ${c.typecheck}`] : []),
    ...(c.test ? [`      - name: Tests`, `        run: ${c.test}`] : []),
    ...(acc ? [`      - name: Acceptance tests`, `        run: ${acc}`] : []),
    '      - name: Ghostship audit (records, locks, approvals)', '        run: node .ghostship/core/runtime/gs.mjs audit',
  ];
  const yml = ['# Generated by Ghostship (gs ci init). Runs what Ghostship runs locally, on every push and pull request.', 'name: ghostship',
    'on:', '  push:', '    branches: [main, develop]', '  pull_request:', 'jobs:', '  verify:', '    runs-on: ubuntu-latest', '    steps:', ...steps, ''].join('\n');
  const rel = '.github/workflows/ghostship.yml';
  mkdirSync(join(root, '.github/workflows'), { recursive: true });
  writeFileSync(join(root, rel), yml);
  return { path: rel };
}

export function currentVersion(root) {
  const r = tryGit(root, ['describe', '--tags', '--abbrev=0', '--match', 'v[0-9]*']);
  return r.ok ? r.out : 'unreleased';
}
